# Generated by Django 4.0.4 on 2022-06-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('flat', 'flat'), ('percent', 'percent')], max_length=10, null=True),
        ),
    ]
