# Generated by Django 4.0.4 on 2022-05-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'Smoked Meats'), ('2', 'Unmixed Natural Rice'), ('3', 'Condiments'), ('4', 'Ready To Eat')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('1', 'KG'), ('2', 'Grams')], max_length=20, null=True),
        ),
    ]
