# Generated by Django 4.0.4 on 2022-05-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('order_accepted', 'Order Accepted'), ('cooking', 'Cooking'), ('outForDelivery', 'Out For Delivery'), ('delivered', 'Delivered')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('smoked_meats', 'Smoked Meats'), ('natural_rice', 'Unmixed Natural Rice'), ('condiments', 'Condiments'), ('ready_to_eat', 'Ready To Eat')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('kg', 'KG'), ('gm', 'Grams')], max_length=20, null=True),
        ),
    ]
